### ISSUE TITLE
Facing issues with the similarity of the text not scored appropriately.

### ISSUE THREAD

**Issue by JafferWilson** [gpoulter/python-ngram#11]
Respected Repository owner,
I have used your library with my Python 3.6 for similarity comparison between the texts. Kindly have a look at the scenario that has not properly been scored as per me: 
```
    >>> ngram.NGram.compare('alexp','Alex Cho',N=1)*100
    30.0
    >>>
    >>> ngram.NGram.compare('alexp','Alex Plutzer',N=1)*100
    21.428571428571427
    >>> ngram.NGram.compare('alexp','Alex Plutzer'.lower(),N=1)*100
    41.66666666666667
    >>> ngram.NGram.compare('alexp','Alex Cho'.lower(),N=1)*100
    44.44444444444444
    >>> ngram.NGram.compare('alexp','AlexCho'.lower(),N=1)*100
    50.0
    >>> ngram.NGram.compare('alexp','AlexPlutzer'.lower(),N=1)*100
    45.45454545454545
```
The most similar must be the one having `alexp` i.e. `Alex Plutzer` but the more score is getting assigned to the former one i.e. `Alex Cho`    
What might be done to get an appropriate result, where I get to have the output as `Alex Plutzer` with high score as compare to the competitive one?
I have also raised a similar question on [Stackoverflow](https://stackoverflow.com/questions/45454668/ngrams-results-are-surprising-python). PLease do tell me.

**Comment by gpoulter** [comment]
Hi Jaffer,

Thank you for the report - I've been on vacation but find time now to
respond.

I believe "alex cho" is more similar to "alexp" im the character unigram
case because it contains fewer differing characters than does "alex
plutzer" - the latter has one additional matching character, but 3
additional non matching characters.

I don't believe ngram similarity is appropriate for the task of matching
such abbreviated user names to the full name.

Graham

**Comment by JafferWilson** [comment]
Thank you for your reply, Graham. My apologies for disturbing you in your vacation time.
But it was a bit important for me to know what is the reason behind not achieving the result I expect.
Now I got the point from your explanation. Once again thank you for your reply.
