### ISSUE TITLE
Implement N-Gram smoothing functions

### ISSUE THREAD

**Issue by gmcquillan** [gpoulter/python-ngram#5]
Something like Modified kneser-ney:

https://code.google.com/p/authorship-attribution/source/browse/trunk/python/kneserney.py?r=48

**Comment by gpoulter** [comment]
Sorry, I missed this when it was filed and haven't checked back.
That repository is gone.

However, I assume you mean something like this: http://smithamilli.com/blog/kneser-ney/

That would be quite a function to add, to predict the probability of a given n-gram, and seems rather specialized.  The intention here was to make a fuzzily searchable set rather than provide a range of Natural Language Processing facilities, so don't think I'll be adding it.
